version: '2'

services:
  app:
    image: 'project:latest'
    build:
      context: .
    container_name: 'app'
    ports:
      - "8080:8080"
    depends_on:
      - db
      - activemq
    environment:
      - SERVER_PORT=8080
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/final_project
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_ACTIVEMQ_URL=tcp://localhost:61616
      - SPRING_ACTIVEMQ_USERNAME=admin
      - SPRING_ACTIVEMQ_PASSWORD=admin

  db:
    image: mysql:latest
    container_name: db
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=final_project

  activemq:
    image: apache/activemq-classic:latest
    container_name: activemq
    ports:
      - "61616:61616"
      - "8161:8161"
    environment:
      - ACTIVEMQ_NAME=activemq
      - ACTIVEMQ_USERNAME=admin
      - ACTIVEMQ_PASSWORD=admin
